// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR6ZKzP-4Y25ui-gI0U_exYZlgWwT1l-8',
    appId: '1:683532179533:web:360ee67e920f3c851de404',
    messagingSenderId: '683532179533',
    projectId: 'tiktok-17069',
    authDomain: 'tiktok-17069.firebaseapp.com',
    storageBucket: 'tiktok-17069.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrwLetfhmh7QWh0awZ1fUjw35ehjocFHc',
    appId: '1:683532179533:android:1ccdf928d9e9ca7f1de404',
    messagingSenderId: '683532179533',
    projectId: 'tiktok-17069',
    storageBucket: 'tiktok-17069.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmGGeQ1xsMpsVPcLPdubeGDnpACFTQNuo',
    appId: '1:683532179533:ios:5f3b0043f0a29c9a1de404',
    messagingSenderId: '683532179533',
    projectId: 'tiktok-17069',
    storageBucket: 'tiktok-17069.appspot.com',
    iosBundleId: 'com.example.ticTok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmGGeQ1xsMpsVPcLPdubeGDnpACFTQNuo',
    appId: '1:683532179533:ios:5f3b0043f0a29c9a1de404',
    messagingSenderId: '683532179533',
    projectId: 'tiktok-17069',
    storageBucket: 'tiktok-17069.appspot.com',
    iosBundleId: 'com.example.ticTok',
  );
}
